### ISSUE TITLE
Rauru Varient Bug

### ISSUE THREAD

**Issue by willyuewu** [Melechtna/SotAW-Improvement-TotK#1]
As [einbob](https://gamebanana.com/members/2524442) pointed on gamebanana, the Rauru varient will cause the game to blackscreen and will not load. 
This is due to a typo of "ResitLightning" which should be "ResistLightning".

**Comment by Melechtna** [comment]
> As [einbob](https://gamebanana.com/members/2524442) pointed on gamebanana, the Rauru varient will cause the game to blackscreen and will not load. This is due to a typo of "ResitLightning" which should be "ResistLightning".

The values were copied from another set
![Screenshot_20230616_183632](https://github.com/Melechtna/SotAW-Improvement-TotK/assets/81296467/049b7c0a-dc0d-4f8d-9fec-56098295763f)

Unless you want to tell me that the game doesn't load with the normal rubber set unmodded, this is how it's spelled normally. It also works perfectly fine for myself and many others. The screen shot was taken from a completely unmodified ArmorEffect bgyml.

Blame Nintendo for this one, if the mod isn't working for you, you either have a conflict, an improperly modded switch, or some other issue that isn't specifically with my mod. The mod works in Yuzu and on Switch. Probably in Ryujinx, but as far as I can tell they've completely broken it for my system until they're done going mental over Apple.

**Comment by willyuewu** [comment]
Thanks for the reply! I guess its I did changed this word and resolved the black screen. But I think I do have another mod calling this same effect. I will give it a try with no other mods and report back.

**Comment by Melechtna** [comment]
> Thanks for the reply! I guess its I did changed this word and resolved the black screen. But I think I do have another mod calling this same effect. I will give it a try with no other mods and report back.

If anything else modifies the armors textures, functionality, or modifies the restbl, you'll have to make a "unified" restbl with all of your other mods that are making edits. The edits I've made in the restbl were provided in another post on the Gamebanana page. Always use the latest NX-Editor, and it should produce a perfectly functional set of mods, so long as the files don't overlap, but the chances of anything else besides the resource table or the armor effects, overlapping with mine are slim.

**Comment by willyuewu** [comment]
After some testing, I found that the PristineWeaponShop is also using the ResourceSizeTable. After I closed that mod, no black screen is there anymore and the clothe can show correctly.
It still baffles me that when I change ResitLightning to ResistLightning, the black screen will be gone. But due to that mod using ResourceSizeTable, the clothe will not be displayed correctly.

Thanks for the help! Really like the look of your design!

**Comment by Melechtna** [comment]
> After some testing, I found that the PristineWeaponShop is also using the ResourceSizeTable. After I closed that mod, no black screen is there anymore and the clothe can show correctly. It still baffles me that when I change ResitLightning to ResistLightning, the black screen will be gone. But due to that mod using ResourceSizeTable, the clothe will not be displayed correctly.
> 
> Thanks for the help! Really like the look of your design!

That could be for a few reasons, the most likely of which being that it invalidates the file because it contains a non-existent variable.

**Comment by willyuewu** [comment]
Oh, another thought. I don't know if you know the other mods that adds effect to sets. Like: https://gamebanana.com/mods/447812.
Using them will invalidate the set bonus on the original armor. But your mod will not. I am really curious why this is the case. 

Thanks!

**Comment by Melechtna** [comment]
> Oh, another thought. I don't know if you know the other mods that adds effect to sets. Like: https://gamebanana.com/mods/447812. Using them will invalidate the set bonus on the original armor. But your mod will not. I am really curious why this is the case.
> 
> Thanks!

One thing I've noticed is that other mods tend to trim out everything but their edits, my guess is to try to prevent issues, but I don't THINK they realize this actually removes the set bonuses from everything else, as the file gets functionally replaced by their own.
