### ISSUE TITLE
I have no other way to bring this information to you aside from the Gamebanana page, See below

### ISSUE THREAD

**Issue by FridayRemada** [Melechtna/SotAW-Improvement-TotK#2]
It doesnt appear to work with Yuzu 1.1.0, even following the renaming of the File both with 110.rztable whatever and also fixing a typo mentioned here in the comments. (SOLUTION: It turns out "rauru variant" has a typo inside "SeriesArmorEffectParamList". it reads "ResitLightning" instead of "ResistLightning".)

I just acquired the armor and it does the same thing as the puffy jacket mod does, which puts you into an infinite loading cycle once you equip the armor. I tried disabling every single mod (barring the update for 1.1.0 and visual fixes) and found no conflicting ones save for the Emulator. 

Was it simply not built for an emulator?

**Comment by Melechtna** [comment]
https://github.com/Melechtna/SotAW-Improvement-TotK/issues/1
