### ISSUE TITLE
Armor bonuses not applying?

### ISSUE THREAD

**Issue by Bananarain** [Melechtna/SotAW-Improvement-TotK#3]
The effect bonuses seem to not be applying when I wear the armor, is there any solution for this?

**Comment by Melechtna** [comment]
Have you actually upgraded it to get the set bonus? The effects can only be applied to the set bonus because of how this armor is setup in the game, so you have to get the basic 2 upgrades to actually get the effects.

**Comment by Bananarain** [comment]
Yeah I just tried to do that and it applied. Very cool mod and and thank you for confirming the issue that I had!
